5+5
x<-42
y<-5
x+y
12->z
a->16
a=16
18->
b  
18->b
a/b
a*y
myapples<-6
myoranges=8
mybasket=myapples+myoranges
myapples1=14
myoranges1="nine"
myfruits=myapples1+myoranges1
x%%y
x%/%y
x>y
x==y
x!=y
ad<-c(2,7,13,19)
ad
a*5
ad*5
class(myoranges1)
class(ad)
z<-x>y
class(z)
ad1=c(1:11)
ad2=c(1:10, times=2)
class(ad2)
rep(1:5, times=2)
c(1:5, times=2)
b=rep(1:5, times=2)
b[3]
b[8]
d<-b[6]
b[16]
b[-3]
b[1:3]
b[2:5 -3]
b[c(2,4,6,8)]
mymatrix1<-matrix(c(1,1,5,1,2,1,4,1,2,2,4,3,3,3,3,4),nrow=4,ncol=4,byrow=TRUE)
mymatrix1[,c(1,3)]
dim(mymatrix1)
dim(mymatrix)
mymatrix2<-cbind(mymatrix1,c(1:4))
mymatrix4<-rbind(mymatrix2,c(8:12))
n=c(2,3,5)
s=c("a","b","c")
b=c(TRUE,FALSE,TRUE)
df=data.frame(n,s,b)
mylist<-list(1,2,3,4)
getwd()
setwd("C:/Users/Neil Mayur Shah/Desktop/Day1")
setwd("C:/Users/Neil Mayur Shah/Desktop/Day1")
wine<-read.csv("wine.csv")
View(wine)
str(wine)
summary(wine)
model1<-lm(Price~AGST,data=wine)
wine$Price
model1$residuals
sse1<-sum((model1$residuals)^2)
sse1
model2<-lm(Price~AGST+HarvestRain,data=wine)
model2
summary(model2)
model3<-lm(Price~AGST+HarvestRain+WinterRain+Age+FrancePop,data=wine)
model3
summary(model3)
model4<-lm(Price~AGST+WinterRain+HarvestRain+Age,data=wine)
model4
summary(model4)
cor(wine$Age,wine$FrancePop)
cor(wine)
summary(model1)
setwd("C:/Users/Neil Mayur Shah/Desktop/Day1")
wine_test<-read.csv("wine_test.csv")
getwd()
Predicttest<-predict(model4,newdata=wine_test)
summary(Predicttest)
View(wine_test$Price)
setwd("C:/Users/Neil Mayur Shah/Desktop/Day2")
housing<-read.csv("Dataset_Day2_Housing.csv")
View(housing)
str(housing)
head(housing)
tail(housing)
housing<-housing[,-1]
cor(housing)
install.packages("sp")
library(sp)
install.packages("raster")
library(raster)
install.packages("usdm")
library(usdm)
library(raster)
pairs(housing)
vifstep(housing[,-1],th=5)
modelh<-lm(SellingPrice000s~NumberofBathrms+GarageSize,data=housing)
summary(modelh)
NumberofBathrms<-3
GarageSize<-3
df1<-data.frame(NumberofBathrms,GarageSize)
View(df1)
Predicttest<-predict(modelh,newdata=df1)
View(Predicttest)
modelh1<-lm(SellingPrice000s~NumberofBathrms+NumberofBedrms+GarageSize,data=housing)
predict(modelh1,data.frame(NumberofBathrms=4,NumberofBedrms=2,GarageSize=0))
getwd()
setwd("C:/Users/Neil Mayur Shah/Desktop/Day2")
regression<-read.csv("Day2_Case Study_Linear Regression.csv")
View(regression)
str(regression)
summary(regression)
hist(regression$Age)  #gives a histogram for given variable of a dataset#
summary(regression)
regression$Age[is.na(regression$Age)]<-38.35  #we gave mean value of age to all missing values; is.na points to all missing values#
hist(regression$Age)
summary(regression)
regression$Job.Type_employed<-as.numeric(regression$Job.Type=="Employed")   #as.numeric creates a dummy numeric value for this variable#
str(regression)
regression$Job.Type_unemployed<-as.numeric(regression$Job.Type=="Unemployed")
regression$Job.Type_retired<-as.numeric(regression$Job.Type=="Retired")
str(regression)
regression$Marital.Status_yes<-as.numeric(regression$Marital.Status=="Yes")
regression$Marital.Status_no<-as.numeric(regression$Marital.Status=="No")
regression$Education_graduate<-as.numeric(regression$Education=="Graduate")
regression$Education_primary<-as.numeric(regression$Education=="Primary")
regression$Education_secondary<-as.numeric(regression$Education=="Secondry")
str(regression)
regression$Metro.City_yes<-as.numeric(regression$Metro.City=="Yes")
regression$Metro.City_no<-as.numeric(regression$Metro.City=="No")
str(regression)
regression<-regression[,-c(2,3,4,5)] #all older non-numeric variables are removed#
str(regression)
summary(regression)
hist(regression)
hist(regression$Purchase.made)
head(regression)
tail(regression)
boxplot(regression)
bx=boxplot(regression$Age)
bx$stats
quantile(regression$Age,seq(0,1,0.02))
regression$Age<-ifelse(regression$Age>60.5,60.5,regression$Age)
bx
boxplot(bx)
boxplot(regression$Age)
cx=boxplot(regression$Signed.in.since.Days.)
cx$stats
regression$Signed.in.since.Days.<-ifelse(regression$Signed.in.since.Days.<44.5,44.5,regression$Signed.in.since.Days.)
boxplot(regression$Signed.in.since.Days.)
dx=boxplot(regression$Purchase.made)
dx$stats
regression$Purchase.made<-ifelse(regression$Purchase.made>16929.295,16929.295,regression$Purchase.made)
boxplot(regression$Purchase.made)
summary(regression$Purchase.made)
str(regression$Purchase.made)
install.packages("car")
library(car)
scatterplot(regression$Age,regression$Signed.in.since.Days.)
scatterplot(regression$Age,regression$Purchase.made)
install.packages("raster")
library(raster)
install.packages("sp")
install.packages("usdm")
library(sp)
library(raster)
library(usdm)
vifstep(regression[,-3],th=5) #vif removes independent variables which have high collinearity#
library(car)
getwd()
setwd("C:/Users/Neil Mayur Shah/Desktop/Day2")
titanic<-read.csv("Day2_Titanic_Logistic Regression.csv")
View(titanic)
summary(titanic)
hist(titanic$age)
bx<-boxplot(titanic$age)
cor(titanic)
cor(titanic$age)
bx$stats
titanic$age[is.na(titanic$age)]<-28
hist(titanic$age)
titanic$female<-ifelse(titanic$sex=="female",1,0)
titanic$embarked_S<-ifelse(titanic$embarked=="S",1,0)
titanic$embarked_C<-ifelse(titanic$embarked=="C",1,0)
head(titanic$female)
head(titanic$embarked_C)
titanic<-titanic[,-c(3,4,9)]
boxplot(bx)
bx<-boxplot(titanic$age)
bx$stats
34-22
titanic$age<-ifelse(titanic$age<4,4,titanic$age)
titanic$age<-ifelse(titanic$age>52,52,titanic$age)
boxplot(titanic$age)
